<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

final class IdentityPermissionSeeder extends Seeder
{
    public function run(): void
    {
        $definitions = [
            ['identity.user.view', 'identity', ['current_node', 'node_and_descendants'], false, false, false],
            ['identity.user.manage', 'identity', ['current_node', 'node_and_descendants'], false, true, true],
            ['identity.role.view', 'identity', ['current_node', 'node_and_descendants'], false, false, false],
            ['identity.role.manage', 'identity', ['current_node', 'node_and_descendants'], false, true, true],
            ['identity.role_assignment.view', 'identity', ['current_node', 'node_and_descendants', 'selected_child'], false, false, false],
            ['identity.role_assignment.request', 'identity', ['current_node', 'node_and_descendants', 'selected_child'], false, true, true],
            ['identity.role_assignment.approve', 'identity', ['current_node', 'node_and_descendants', 'selected_child'], false, true, true],
            ['identity.delegation.view', 'identity', ['current_node', 'node_and_descendants', 'selected_child'], true, false, false],
            ['identity.delegation.request', 'identity', ['current_node', 'node_and_descendants', 'selected_child', 'explicit_record'], true, true, true],
            ['identity.delegation.approve', 'identity', ['current_node', 'node_and_descendants', 'selected_child'], false, true, true],
            ['identity.access_review.manage', 'identity', ['current_node', 'node_and_descendants'], false, true, true],
            ['identity.audit.view', 'identity', ['current_node', 'node_and_descendants'], false, true, false],
            ['identity.break_glass.request', 'identity', ['current_node', 'node_and_descendants'], false, true, false],
            ['identity.break_glass.review', 'identity', ['current_node', 'node_and_descendants'], false, true, true],
            ['audit.event.view', 'audit', ['current_node', 'node_and_descendants'], false, true, false],
            ['audit.event.export', 'audit', ['current_node', 'node_and_descendants'], false, true, true],
            ['audit.integrity.verify', 'audit', ['current_node', 'node_and_descendants'], false, true, false],
            ['document.upload', 'documents', ['current_node', 'node_and_descendants', 'explicit_record'], true, false, false],
            ['document.view', 'documents', ['current_node', 'node_and_descendants', 'explicit_record'], true, false, false],
            ['document.download', 'documents', ['current_node', 'node_and_descendants', 'explicit_record'], true, true, false],
            ['document.replace', 'documents', ['current_node', 'node_and_descendants', 'explicit_record'], true, true, false],
            ['document.archive', 'documents', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, true],
            ['document.verify', 'documents', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, true],
            ['workflow.view', 'workflow', ['current_node', 'node_and_descendants'], true, false, false],
            ['workflow.configure', 'workflow', ['current_node', 'node_and_descendants'], false, true, true],
            ['workflow.approve', 'workflow', ['current_node', 'node_and_descendants'], false, true, true],
            ['notification.view', 'notifications', ['current_node', 'node_and_descendants'], false, false, false],
            ['notification.template.manage', 'notifications', ['current_node', 'node_and_descendants'], false, true, true],
            ['outbox.view', 'operations', ['current_node', 'node_and_descendants'], false, true, false],
            ['outbox.replay', 'operations', ['current_node', 'node_and_descendants'], false, true, true],
            ['fleet.reference.view', 'fleet', ['current_node', 'node_and_descendants'], false, false, false],
            ['fleet.reference.manage', 'fleet', ['current_node', 'node_and_descendants'], false, true, true],
            ['fleet.dashboard.view', 'fleet', ['current_node', 'node_and_descendants'], false, false, false],
            ['vehicle.view', 'fleet', ['current_node', 'node_and_descendants', 'explicit_record'], true, false, false],
            ['vehicle.create', 'fleet', ['current_node', 'node_and_descendants'], false, true, false],
            ['vehicle.status.manage', 'fleet', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, true],
            ['vehicle.transfer', 'fleet', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, true],
            ['vehicle.transfer.receive', 'fleet', ['current_node', 'node_and_descendants'], false, true, true],
            ['vehicle.odometer.record', 'fleet', ['current_node', 'node_and_descendants', 'explicit_record'], true, false, false],
            ['vehicle.plate.manage', 'fleet', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, true],
            ['vehicle.fleet.assign', 'fleet', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, true],
            ['vehicle.compliance.manage', 'fleet', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, true],
            ['driver.view', 'fleet', ['current_node', 'node_and_descendants', 'explicit_record'], true, false, false],
            ['driver.create', 'fleet', ['current_node', 'node_and_descendants'], false, true, false],
            ['driver.status.manage', 'fleet', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, true],
            ['driver.licence.manage', 'fleet', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, true],
            ['assignment.view', 'fleet', ['current_node', 'node_and_descendants', 'explicit_record'], true, false, false],
            ['assignment.create', 'fleet', ['current_node', 'node_and_descendants'], false, true, true],
            ['assignment.close', 'fleet', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, true],
            ['assignment.own.view', 'fleet', ['current_node'], false, false, false],
            ['assignment.own.acknowledge', 'fleet', ['current_node'], false, false, false],
            ['geography.dashboard.view', 'geography', ['current_node', 'node_and_descendants'], false, false, false],
            ['geography.reference.view', 'geography', ['current_node', 'node_and_descendants'], true, false, false],
            ['geography.reference.manage', 'geography', ['current_node', 'node_and_descendants'], false, true, true],
            ['place.view', 'geography', ['current_node', 'node_and_descendants', 'explicit_record'], true, false, false],
            ['place.manage', 'geography', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, false],
            ['place.approve', 'geography', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, true],
            ['place.hierarchy.manage', 'geography', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, true],
            ['place.policy.manage', 'geography', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, false],
            ['place.policy.approve', 'geography', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, true],
            ['route.view', 'geography', ['current_node', 'node_and_descendants', 'explicit_record'], true, false, false],
            ['route.manage', 'geography', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, false],
            ['route.approve', 'geography', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, true],
            ['distance.view', 'geography', ['current_node', 'node_and_descendants', 'explicit_record'], true, false, false],
            ['distance.manage', 'geography', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, false],
            ['distance.approve', 'geography', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, true],
            ['geography.zone.view', 'geography', ['current_node', 'node_and_descendants'], true, false, false],
            ['geography.zone.manage', 'geography', ['current_node', 'node_and_descendants'], false, true, true],
            ['geography.import.manage', 'geography', ['current_node', 'node_and_descendants'], false, true, true],
            ['geography.import.approve', 'geography', ['current_node', 'node_and_descendants', 'explicit_record'], false, true, true],
            ['geography.own.view', 'geography', ['current_node'], false, false, false],
            // ── Milestone 7: Mobile device management ───────────────────────────
            ['mobile.device.view', 'mobile', ['current_node', 'node_and_descendants'], false, false, false],
            ['mobile.device.enroll', 'mobile', ['current_node', 'node_and_descendants'], false, true, false],
            ['mobile.device.approve', 'mobile', ['current_node', 'node_and_descendants'], false, true, true],
            ['mobile.device.reject', 'mobile', ['current_node', 'node_and_descendants'], false, true, true],
            ['mobile.device.activate', 'mobile', ['current_node', 'node_and_descendants'], false, true, true],
            ['mobile.device.suspend', 'mobile', ['current_node', 'node_and_descendants'], false, true, true],
            ['mobile.device.revoke', 'mobile', ['current_node', 'node_and_descendants'], false, true, true],
            ['mobile.device.replace', 'mobile', ['current_node', 'node_and_descendants'], false, true, true],
            ['mobile.device.retire', 'mobile', ['current_node', 'node_and_descendants'], false, true, true],
            ['mobile.device.assign', 'mobile', ['current_node', 'node_and_descendants'], false, true, true],
            ['mobile.device.remote_sign_out', 'mobile', ['current_node', 'node_and_descendants'], false, true, true],
            ['mobile.device.cache_reset', 'mobile', ['current_node', 'node_and_descendants'], false, true, true],
            ['mobile.device.history.view', 'mobile', ['current_node', 'node_and_descendants'], false, false, false],
            ['mobile.device.diagnostics.view', 'mobile', ['current_node', 'node_and_descendants'], false, false, false],
            ['mobile.sync.view', 'mobile', ['current_node', 'node_and_descendants'], false, false, false],
            ['mobile.sync.manage', 'mobile', ['current_node', 'node_and_descendants'], false, true, true],
            ['mobile.policy.view', 'mobile', ['current_node', 'node_and_descendants'], false, false, false],
            ['mobile.policy.manage', 'mobile', ['current_node', 'node_and_descendants'], false, true, true],
        ];


        foreach ($definitions as [$code, $domain, $scopeModes, $delegable, $requiresMfa, $makerChecker]) {
            DB::table('permissions')->insertOrIgnore([
                'id' => (string) Str::ulid(),
                'code' => $code,
                'domain' => $domain,
                'description' => str_replace('.', ' ', ucfirst($code)),
                'allowed_scope_modes' => json_encode($scopeModes, JSON_THROW_ON_ERROR),
                'resource_types' => null,
                'delegable' => $delegable,
                'requires_mfa' => $requiresMfa,
                'requires_step_up' => $requiresMfa,
                'maker_checker_required' => $makerChecker,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
