import type { en } from "./en";

// Human review required before production.
export const am: Record<keyof typeof en, string> = {
  "app.name": "የኦሮሚያ ተሽከርካሪ አስተዳደር",
  "nav.home": "መነሻ",
  "nav.profile": "መገለጫ",
  "nav.language": "ቋንቋ",
  "nav.skip": "[HUMAN_REVIEW] ወደ ዋናው ይዘት ዝለል",
  "auth.signIn": "ግባ",
  "auth.integrationPending": "[HUMAN_REVIEW] ማረጋገጫ በMilestone 3 ይገናኛል።",
  "dashboard.title": "የመድረክ መሠረት",
  "dashboard.description": "[HUMAN_REVIEW] የሥራ ዳሽቦርዶች በተፈቀደው ደረጃ ይጨመራሉ።",
  "state.loading": "በመጫን ላይ",
  "state.empty": "የመድረክ መረጃ የለም።",
  "state.unauthorized": "መግባት ያስፈልጋል።",
  "state.forbidden": "ይህን ገጽ ለማየት ፈቃድ የለዎትም።",
  "state.notFound": "የተጠየቀው ገጽ አልተገኘም።",
  "state.unavailable": "አገልግሎቱ ለጊዜው አይገኝም።",
  "state.serviceUnavailable": "[HUMAN_REVIEW] አገልግሎቱ አይገኝም",
  "state.offline": "ከመስመር ውጭ",
  "state.online": "በመስመር ላይ",
  "state.forcedUpdate": "[HUMAN_REVIEW] የተፈቀደ የመተግበሪያ ዝማኔ ያስፈልጋል።",
  "state.revokedDevice": "[HUMAN_REVIEW] ይህ መሣሪያ ከእንግዲህ አልተፈቀደም።",
  "state.enrollmentRequired": "[HUMAN_REVIEW] የመሣሪያ ምዝገባ ያስፈልጋል።",
  "sync.title": "የማመሳሰል ሁኔታ",
  "sync.noPending": "በመጠባበቅ ላይ ያለ ነገር የለም።",
  "support.title": "ድጋፍ",
  "support.reference": "[HUMAN_REVIEW] ድጋፍ ሲጠይቁ የድጋፍ ማጣቀሻውን ያቅርቡ።",
  "profile.title": "መገለጫ",
  "language.en": "English",
  "language.om": "Afaan Oromoo",
  "language.am": "አማርኛ",
};
