export const en = {
  "app.name": "Oromia Fleet Management",
  "nav.home": "Home",
  "nav.profile": "Profile",
  "nav.language": "Language",
  "nav.skip": "Skip to main content",
  "auth.signIn": "Sign in",
  "auth.integrationPending": "Authentication will be connected in Milestone 3.",
  "dashboard.title": "Platform foundation",
  "dashboard.description":
    "Business dashboards will be added in their approved milestones.",
  "state.loading": "Loading",
  "state.empty": "No platform information is available.",
  "state.unauthorized": "Sign in is required.",
  "state.forbidden": "You do not have permission to view this page.",
  "state.notFound": "The requested page was not found.",
  "state.unavailable": "The service is temporarily unavailable.",
  "state.serviceUnavailable": "Service unavailable",
  "state.offline": "Offline",
  "state.online": "Online",
  "state.forcedUpdate": "An approved application update is required.",
  "state.revokedDevice": "This device is no longer authorized.",
  "state.enrollmentRequired": "Device enrollment is required.",
  "sync.title": "Synchronization status",
  "sync.noPending": "No pending items.",
  "support.title": "Support",
  "support.reference": "Provide the support reference when requesting help.",
  "profile.title": "Profile",
  "language.en": "English",
  "language.om": "Afaan Oromoo",
  "language.am": "Amharic",
} as const;
